---
name: Deploy

concurrency: production

on:
  workflow_dispatch:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install mkdocs
        run: pip install mkdocs-material

      - name: Build wiki from source
        run: cd wiki && mkdocs build -d ../public/wiki

      - name: Set up ssh
        run: |
          eval $(ssh-agent -s)
          echo "${{ secrets.DEPLOY_SSH_KEY }}" | ssh-add -

          test ! -d ~/.ssh && mkdir ~/.ssh; chmod 700 ~/.ssh
          cat >> ~/.ssh/known_hosts <<< '${{ secrets.DEPLOY_SSH_FINGERPRINT }}'

          echo SSH_AUTH_SOCK=$SSH_AUTH_SOCK >> $GITHUB_ENV

      - name: Copy files to server
        run: |
          rsync -e 'ssh -p ${{ secrets.DEPLOY_SSH_PORT }}' -avzi --delete --delete-excluded \
            public/ ${{ secrets.DEPLOY_SSH_USERHOST }}:${{ secrets.DEPLOY_PATH }}/
