name: Build and deploy

on:
  workflow_dispatch:
  push: { branches: master }

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - run: |
          eval $(ssh-agent -s)
          echo "${{ secrets.DEPLOY_KEY }}" | ssh-add -
          test ! -d ~/.ssh && mkdir ~/.ssh
          chmod 700 ~/.ssh
          cat >> ~/.ssh/known_hosts <<< '${{ secrets.DEPLOY_FINGERPRINT }}'
          
          rsync -avzi --delete --delete-excluded \
            public/ ${{ secrets.DEPLOY_USERHOST }}:${{ secrets.DEPLOY_PATH }}/
